spring.application.name=utility-billing-system
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/ubs
spring.datasource.username=postgres
spring.datasource.password=love
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.sql.init.mode=never

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha

app.jwt.secret=ChangeThisSecretToAtLeastThirtyTwoCharactersForProduction
app.jwt.access-minutes=30
app.jwt.refresh-days=7
app.otp.minutes=10

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ishemalove@gmail.com
spring.mail.password=wwcb gswo icqd thul
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000

app.mail.from=ishemalove@gmail.com
app.mail.from-name=UBS system
